# Generated by Django 3.2 on 2023-09-09 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tbl_almacen',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('categoria', models.IntegerField(choices=[(1, 'FERRETERIA'), (2, 'CONSTRUCCION')], default=1)),
            ],
            options={
                'db_table': 'tbl_producto',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.IntegerField(choices=[(1, 'INGRESO'), (2, 'EGRESO')], default=1)),
                ('cantidad', models.IntegerField(default=1)),
                ('fecha', models.DateField(auto_now=True)),
                ('saldo', models.IntegerField(null=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.almacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.producto')),
            ],
            options={
                'db_table': 'tbl_movimiento',
            },
        ),
    ]
